language: csharp
mono: none
dotnet: 2.0.2
dist: trusty
script:
 - dotnet restore
 - dotnet build --configuration=Release
 - dotnet test --configuration=Release ./tests/Rlx.Tests/
 - dotnet pack --configuration=Release --verison-suffix="beta$TRAVIS_BUILD_ID" ./src/Rlx/
 